export * from './home/HomePage';
export * from './contact/ContactPage';
export * from './profile/ProfilePage';
export * from './marketplace/MarketPage';
export * from './error/ErrorPage';
export * from './login/LoginPage';
export * from './register/RegisterPage';
export * from './admin/HomeAdminPage';
export * from './professionals/HomePagePro'